#FROM python:3.12-slim
FROM python:3.12-slim-bookworm
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app_secure ./app_secure
EXPOSE 5000
#RUN useradd -m -u 1000 appuser
#USER appuser
CMD ["python", "-m", "app_secure"]
